version: "3"
services:
   elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    hostname: elasticsearch
    environment:
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
   logstash:
    image: docker.elastic.co/logstash/logstash:5.5.3
    hostname: logstash
    ports:
      - "5044:5044"
   kibana:
    image: docker.elastic.co/kibana/kibana:5.5.3
    hostname: kibana
    environment:
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
